In [11]:
print('hello')

hello

In [12]:
import calc
calc.add(10,20)

30

In [13]:
print(calc.add(10,20))

30

In [7]:
from calc import add
add(2, 3)

5

In [2]:
from calc import add, multiply

print(add(2, 3))
print(multiply(2, 3))
print(subtract(10, 3))

5
6
7

In [1]:
from calc import subtract
print(subtract(10, 3))

7

# 모듈 정의하기

1. calc.py 모듈 만들기
2. 모듈내에 함수 정의 - add()

# 모듈 가져오기

import 모듈이름 as 별명
from 모듈 import 함수, 함수2
from 모듈 import *


# 모듈 단독으로 실행

 터미널에서
 '''
 python calc.py 
 실행
 '''

if __name__ == '__main__':
   #실행 내용을 넣어준다
   print('hi')

In [ ]:
import calc as cc # calc = cc로 지정했다
print(cc.add(10,5))

15

In [ ]:
from calc import subtract
subtract(10, 3)

7

# math 수학 함수

In [6]:
import math
print(math.sqrt(16))

4.0

# random 랜덤값 생성

In [11]:
import random
print(random.randint(1, 1000))

738

# data time 날짜·시간 처리

In [13]:
import datetime
datetime.datetime.now()

datetime.datetime(2026, 8, 10, 10, 46, 26, 423219)

# os 컴퓨터의 폴더·파일 (운영체제 관련 기능)

In [14]:
import os
print(os.getcwd())

c:\study\python-basic

# sys 파이썬 정보 (시스템 관련 정보)

In [15]:
import sys
print(sys.version)

3.13.15 (tags/v3.13.15:4061bc4, Aug  5 2026, 13:05:39) [MSC v.1944 64 bit (AMD64)]

# time 시간 기다리기 (시간 관련 기능)

In [16]:
import time
print("시작")
time.sleep(3)
print("끝")

시작
끝

# 라이브러리 가져오기
1. pip install
2. import 라이브러리

In [ ]:
import requests

In [ ]:
requests.get("https://www.google.com")

# 판다스 라이브러리 사용하기

pip install pandas

In [ ]:
# 라이브러리 호출
import pandas as pd

# 표로 보기위한 원시 데이터(딕셔너리)
data = {
    '이름': ['김철수', '이영희', '박민수', '정수진', '최영호', '한미래', '윤지원'],
    '나이': [25, 28, 22, 31, 27, 24, 29],
    '점수': [85, 92, 78, 95, 88, 73, 91]
}

In [6]:
# 판다스의 데이터프레임객체 생성
df = pd.DataFrame(data)
# 상위 5개 데이터 조회
#df.head()

    이름  나이  점수
0  김철수  25  85
1  이영희  28  92
2  박민수  22  78
3  정수진  31  95
4  최영호  27  88

In [10]:
# df 의 나이 속성의 평균을 구하세요
int(df["나이"].mean())

26

In [11]:
df.describe()

              나이         점수
count   7.000000   7.000000
mean   26.571429  86.000000
std     3.101459   7.958224
min    22.000000  73.000000
25%    24.500000  81.500000
50%    27.000000  88.000000
75%    28.500000  91.500000
max    31.000000  95.000000

# 패키지

모듈의 집합 > 디렉토리(폴더)로 묶어준다

C:\study\python-basic\my_first_package

모듈을 호출하는 코드 C:\study\python-basic\my_first_package\main_app.py  

모듈은 패키지 magic_calc에 포함:  

C:\study\python-basic\my_first_package\magic_calc\basic_ops.py  
C:\study\python-basic\my_first_package\magic_calc\advanced_ops.py